site_name: MkDocs CMS
theme: material

extra:
  social:
    - type: 'github'
      link: 'https://github.com/capriosa'
    - type: 'twitter'
      link: 'https://twitter.com/mdwp'
    - type: 'facebook'
      link: 'https://facebook.com/mdwp.de'
repo_name: 'capriosa/mkdocs-cms'
repo_url: 'https://github.com/capriosa/mkdocs-cms'