backend:
  name: github
  repo: capriosa/mkdocs-cms
  branch: master

public_folder: "site"
media_folder: "site/assets"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    sort: "date:desc" # Default is title:asc
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}